// import React from 'react'

export { default as Cart } from './Cart'

// // import Card from './Card'
export { default as Card } from './Card'

// import FormTemplate from './form'
export { default as FormTemplate } from './form'
// import AddToCartLg from './AddToCartLg'
export { default as AddToCartLg } from './AddToCartLg'
export { default as AddToCartSm } from './AddToCartSm'
// import AddToFavoritesLg from './ AddToFavoritesLg'
export { default as AddToFavoritesLg } from './AddToFavoritesLg'
// import ContinueShoppingLg from './ContinueShoppingLg'
export { default as ContinueShoppingLg } from './ContinueShoppingLg'
// import EventRegistration from './EventRegistration'
export { default as EventRegistration } from './EventRegistration'
// import ActivityReservation from './ActivityReservation'
export { default as ActivityReservation } from './ActivityReservation'
// import MoreRound from './MoreRound'
export { default as MoreRound } from './MoreRound'
// import MoreSquare from './MoreSquare'
export { default as MoreSquare } from './MoreSquare'
// import NextStepLg from './NextStepLg'
export { default as NextStepLg } from './NextStepLg'
// import QuantitySelector from './QuantitySelector'
export { default as QuantitySelector } from './QuantitySelector'
export { default as BackToPrevious } from './BackToPrevious'

export { default as Step } from './Step'
export { default as PreviousStep } from './PreviousStep'
export { default as SquareAccounts } from './SquareAccounts'
// import SignUp from './SignUp'
export { default as SignUp } from './SignUp'
// import DetailSignUp from './DetailSignUp'
export { default as DetailSignUp } from './DetailSignUp'

export { default as Heart } from './Heart'
export { default as HomehotelGallery } from './HomehotelGallery'

